### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by X-Ryl669** [formatc1702/WireViz#2]
I'd like to thank you for this software, it's really clean!

**Comment by formatc1702** [comment]
Wow, this project really blew up! I really appreciate the support and the kind words, so thank you everybody!

**Comment by Marsfan** [comment]
@formatc1702  I know that this is closed, but I just wanted to let you know that it probably blew up because someone brought it to the attention of Hackaday and it got an article there:
https://hackaday.com/2020/06/23/an-open-source-tool-to-document-your-wiring/
I also want to thank you as well, as I have a project that has been struggling to figure out how to document wiring for a while, and this appears to be a solution.
