### ISSUE TITLE
How to create an alternating sides daisy chain without templates?

### ISSUE THREAD

**Issue by hyphz** [formatc1702/WireViz#209]
The "alternating sides" daisy chain example also introduces a template syntax which is rather confusing as I'm not sure how to use one without the other. It seems to involve a "<<" member of the dict but it is not clear if this has to be on the connector, the wire, both, or what. Could the documentation on this be clarified?

**Comment by kvid** [comment]
> The "alternating sides" daisy chain example also introduces a template syntax which is rather confusing as I'm not sure how to use one without the other. It seems to involve a "<<" member of the dict but it is not clear if this has to be on the connector, the wire, both, or what. Could the documentation on this be clarified?

The [documentation](https://github.com/formatc1702/WireViz/blob/master/docs/syntax.md#inheritance) has a link to a page describing the anchor consept in general YAML files. I recommend reading that page. That consept is useful when several connectors or cables share a set of common attribute values.

**Comment by hyphz** [comment]
That is very helpful for the template syntax, but it does not mention the details of the << signifier.

**Comment by kvid** [comment]
> That is very helpful for the template syntax, but it does not mention the details of the << signifier.

Please search for "Extend" in that same page, and you'll find several examples using << to inherit from a template and then extend with other attributes.

**Comment by hyphz** [comment]
Thanks. That is helpful, but in that case, what causes the zig-zagging in the zig zag example to happen? Is it triggered by the use of templates?

**Comment by formatc1702** [comment]
Zig-zagging and templates are completely unrelated.

---

Regarding zig-zagging: Each individual connection set is interpreted as going from left to right.

Look at the [source code](https://github.com/formatc1702/WireViz/blob/master/examples/ex06.yml) for [Example 06](https://github.com/formatc1702/WireViz/blob/master/examples/readme.md#example-06):

Since `X1`, `X3` and `X5` are on the left, and `X2` and `X4` are on the right, the connection sets are defined as follows (ignoring the cables in between):

```
X1 -> X2
X3 -> X2  (going "backwards" in the daisy chain, but "forwards" as in left-to-right)
X3 -> X4
X5 -> X4  (same principle as above)
```

The actual arrangement of the nodes is handled by the GraphViz backend, so there might be cases where the visual output is not exactly what you expect, especially in more complex layouts. Unfortunately, currently there's not much WireViz can do about these cases.

---

Regarding templates, please note that these will not be required for most cases once #186 is finished and merged.

**Comment by hyphz** [comment]
Thanks very much.
