### ISSUE TITLE
Internal Jumper

### ISSUE THREAD

**Issue by alorman** [formatc1702/WireViz#310]
Is there a way to create an internal jumper within a plug?
I've mocked up a very quick demonstration below.

![image](https://user-images.githubusercontent.com/12905418/224560157-72a093d7-d17b-4a21-8eef-22d5fcf5dfb2.png)

I've seen this need in things like Harting connectors and other things that may use the plug presence as a state change. 

Thank you!

**Comment by avenjamin** [comment]
See #286

**Comment by JonMcLin** [comment]
![testJumper](https://user-images.githubusercontent.com/15487472/224710485-54659711-5de0-4097-b7dd-5a9638cb9663.png)

`connectors:
  X1: &bar
    type: Molex Micro-Fit
    subtype: male
    pinlabels: [A, B, C, D]


  X2: &baz
    type: Molex Micro-Fit
    subtype: male
    pinlabels: [Clk, Gnd]


cables:
  W1:
    category: bundle # bundles are routed together, but more loosely than normal cables
    wirecount: 3
    colors: [BK] # if number of items in color list is less than wirecount, loop colors
    gauge: 0.25 mm2
    show_equiv: true
    length: 0.2

connections:
  -
    - X1: [1,2,3,4]
    - W1: [1,1,2,3]

  -
    - W1: [2,3]
    - X2: [1,2]

`

**Comment by alorman** [comment]
Awesome! Thanks all, closing issue

**Comment by kvid** [comment]
@alorman , @avenjamin , @JonMcLin - thank you for contributing with a well described use case, link to an earlier relevant issue, and an alternative solution. This is a great example of the power of a cooperating user community.

In case you haven"t already been notified due to subscribing/watching the relevant issues, I just want to inform you about the recent development in #286 with [a new alternative](https://github.com/formatc1702/WireViz/issues/286#issuecomment-1483701234_) you can try out. Feel free to contribute in such earlier issues aswell.

**Comment by kvid** [comment]
@alorman, @avenjamin, @JonMcLin, and others with similar use cases - I added today a suggested work-around for over-sized loops in https://github.com/wireviz/WireViz/issues/286#issuecomment-2094309143
