### ISSUE TITLE
[internal] Make `Harness.output` method more consistent

### ISSUE THREAD

**Issue by slightlynybbled** [formatc1702/WireViz#82]
Looking at [this line](https://github.com/formatc1702/WireViz/blob/fffb354d7c86cc4f85d1e7e0753a07f7b6a65fa7/src/wireviz/Harness.py#L214)

For anyone who wishes to use `Harness.output` method directly, there is a parameter called `directory`.  If `directory` is utilized, then all of the output files are not saved to the same place (`.bom.tsv` and `.html`).  The workaround is use `filename` with an absolute path and leave `directory` blank.

I am happy to submit a pull request to fix this, but there are two options and I am not sure which the author wishes to engage:

Option 1. Eliminate the `directory` and ensure that `filename` is always a valid path (recommend using `pathlib` and making `filename` and instance of `pathlib.Path`).

Option 2. Insert `directory` into the `.bom.tsv` and `.html` directories.

I look forward to author's guidance on this.

**Comment by formatc1702** [comment]
In the interest of simplicity, I would go for option 1 and eliminate `directory` completely, since it's just as easy to include it in `filename` directly.

This issue is related to #60 (and indirectly, to #55); handling of file output needs some cleaning up.
If you're willing to submit a PR that fixes both issues, I'd be more than happy to include it! Any help in this regard is appreciated :)
